# Week 2 - Mini Assessment

Welcome to your mini assessment for week two. A set of exercises using NumPy to make sure you get accustomed to one of the most widely used libraries in the data analytics/science community.

Once you are done with the notebook, you should try to put it on GitHub under your respective folder for everything related to module 2. In addition let your instructor know that you have submitted this mini-assessment.

1. Import the numpy package and check its version.

2. Create an numpy range of values from 0 to 49 and name it `mynums`. Print its output.

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

3. Reshape the array you created in step 2 into a matrix with the shape below and assign a copy of it to a variable called `my_matrix`. Print the matrix.

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

4. Create a linearly-spaced array of size 100 between the numbers 20 to 100, assign it to the variable, `num_increases` and print it.

array([ 20.        ,  20.80808081,  21.61616162,  22.42424242,
        23.23232323,  24.04040404,  24.84848485,  25.65656566,
        26.46464646,  27.27272727,  28.08080808,  28.88888889,
        29.6969697 ,  30.50505051,  31.31313131,  32.12121212,
        32.92929293,  33.73737374,  34.54545455,  35.35353535,
        36.16161616,  36.96969697,  37.77777778,  38.58585859,
        39.39393939,  40.2020202 ,  41.01010101,  41.81818182,
        42.62626263,  43.43434343,  44.24242424,  45.05050505,
        45.85858586,  46.66666667,  47.47474747,  48.28282828,
        49.09090909,  49.8989899 ,  50.70707071,  51.51515152,
        52.32323232,  53.13131313,  53.93939394,  54.74747475,
        55.55555556,  56.36363636,  57.17171717,  57.97979798,
        58.78787879,  59.5959596 ,  60.4040404 ,  61.21212121,
        62.02020202,  62.82828283,  63.63636364,  64.44444444,
        65.25252525,  66.06060606,  66.86868687,  67.67676768,
        68.48484848,  69.29292929,  70.1010101 ,  70.90

5. Create an numpy array with 20 zeros, assign it to the variable `zeroes`.

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

6. Create a two dimensional array of size 7 by 8 filled with 1s and do the following:
- mulptiply the first rows by 2
- add 3, and raise to the power of two the odd columns starting from the beginning
- subtract 10 and multiply by 15 the elements in the even rows and odd columns

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

array([2., 2., 2., 2., 2., 2., 2., 2.])

array([[16., 16., 16., 16.],
       [16., 16., 16., 16.],
       [16., 16., 16., 16.],
       [16., 16., 16., 16.],
       [16., 16., 16., 16.],
       [16., 16., 16., 16.],
       [16., 16., 16., 16.]])

array([[-135., -135., -135., -135.],
       [-135., -135., -135., -135.],
       [-135., -135., -135., -135.],
       [-135., -135., -135., -135.]])

7. Create a numpy array starting at 20 and ending at 40 with 10 equally spaced values. Print your result.

array([20.        , 22.22222222, 24.44444444, 26.66666667, 28.88888889,
       31.11111111, 33.33333333, 35.55555556, 37.77777778, 40.        ])

8. Create a 9 by 9 matrix with random integers from 100 to 500 and use the dtype "int32".

array([[318, 168, 216, 178, 198, 380, 149, 365, 350],
       [225, 425, 491, 156, 301, 300, 245, 285, 273],
       [214, 225, 449, 421, 256, 444, 376, 233, 482],
       [344, 396, 280, 460, 386, 318, 131, 350, 490],
       [415, 137, 330, 206, 288, 444, 399, 459, 476],
       [244, 152, 375, 211, 116, 216, 397, 120, 201],
       [213, 498, 498, 270, 182, 242, 357, 262, 396],
       [387, 445, 266, 280, 354, 360, 356, 426, 286],
       [210, 365, 118, 269, 101, 364, 320, 484, 298]], dtype=int32)

9. Create an empty array of 20 elements with shape 2 by 10, dtype 'float32' and add a different number to each row.

array([[-2.68156159e+154,  1.49457291e-154,  6.93271142e-310,
         6.93271155e-310,  6.93271142e-310,  6.93271155e-310,
         6.93271155e-310,  6.93271155e-310,  6.93271155e-310,
         6.93271155e-310],
       [ 6.93271155e-310,  6.93271155e-310,  6.93271142e-310,
         6.93271155e-310,  6.93271142e-310,  6.93271155e-310,
         1.49457291e-154, -2.68678346e+154,  6.01346953e-154,
         1.39067116e-308]])

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
[-5. -5. -5. -5. -5. -5. -5. -5. -5. -5.]


10. Create an array with 15 random numbers between 100 and 200 and print the maximum value of the array.

11. Create an array with the following numbers [40, 41, 26, 14, 15, 47, 43, 33, 44, 22], and assign it to a variable
- create a slice from the 5th to 10th element, and assign it to a variable
- change the value of both arrays with any operation you'd like (add, subtract, multiply, etc.), and 
- then print all 3 (the first array and your next two variables).

12. Create an array of 360 random numbers from -10 to 50 (to resemble the weather) and find the min, max, 25th percentile, 75 percentile, average, and the median.

13. Reshape the array you created in step 12 into a matrix of 300 by 12 and get the same values but only for the months this time.

14. Create a mask for your data, and filter out and print:
- the average temperature of the days where the temperature was below 10
- the average temperature of the days where the temperature was greater than 30

15. Create a full 10 by 10 matrix with a number of your choosing and assign it to a variable. After printing that variables, unravel the matrix and assign the array to a new number.